[build]
  command = "npm run build:ssr"
  publish = "dist/client"

[functions]
  included_files = ["dist/server/**", "dist/client/index.html"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200